### ISSUE TITLE
Oops! Something went wrong and we couldn't process your request.

### ISSUE THREAD

**Issue by greg-digit** [SynergyWholesale/WHMCS-Domains-Module#1]
WHMCS version 7.9.1
PHP version 7.2
After upload/extract the folder "synergywholesaledomains" this is the error when viewed in WHMCS Domain Registrars.

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

**Comment by CameronHall** [comment]
Hi @greg-digit,

Can you please provide the output of `php -m`?  Do you have the SOAP module enabled?

If you could please [enable error reporting](https://docs.whmcs.com/Enabling_Error_Reporting) as well so we can get a more detailed error, that could be really helpful.

Thank you :)

**Comment by CameronHall** [comment]
It would appear there is an issue with support for anything less than PHP 7.3 (which is what we tested again) due to a [rogue trailing comma ](https://github.com/SynergyWholesale/WHMCS-Domains-Module/blob/master/modules/registrars/synergywholesaledomains/synergywholesaledomains.php#L800).

I'll update this so it's compatible with older PHP versions and see if we can start running our tests against different PHP versions.

**Comment by CameronHall** [comment]
Hi @greg-digit,

I've release [v2.0.1](https://github.com/SynergyWholesale/WHMCS-Domains-Module/releases/tag/v2.0.1) which addresses this issue.

I've also updated our tests to run against PHP 5.6 through 7.4 to avoid any regressions in the future.

Thanks for reporting!
