### ISSUE TITLE
Domain Pending Transfer Error

### ISSUE THREAD

**Issue by myshophosting** [SynergyWholesale/WHMCS-Domains-Module#10]
I'm getting the following error displayed in red in WHMCS domain tab after transferring a domain:

Registry Error: Data missing

Even If I hit the SYNC button, the error displays. (the domain is pending transfer)

I also had an issue with a new domain registration today - I have created another issue with logs for this.

I can say that CRON renewals etc are working, so its not an issue of connection or API keys etc.

**Comment by myshophosting** [comment]
Here is a copy of the REQUEST/REPLY logs when I hit the sync button and get the error:

REQUEST:
Array
(
    [php_ver] => 7.3.16
    [whmcs_ver] => 7.10.0-rc.2
    [whmcs_mod_ver] => 2.1.2
    [apiKey] => ****************************************************************
    [resellerID] => *****
    [domainName] => XXXXX.com.au
)

REPLY:

stdClass Object
(
    [domainName] => XXXXX.com.au
    [transfer_status] => Pending Registry Completion
    [transfer_completed_by] => 2020-04-04 14:54:54
    [email] => XXXXX@hotmail.com
    [status] => OK_TRANSFER_PENDING
)

Looks good to me, but doesn't explain the error. (could also be WHMCS bug?

**Comment by CameronHall** [comment]
Hey @myshophosting,

Thanks for testing out the latest version, we really appreciate it :)

I've replicated the issue and it appears to be caused by an oversight whilst adding in `GetDomainInformation`. It would appear that the same method is used for pending domain transfers. The trouble is when we wrote it - it wasn't catering for the fact the status of a pending transfer is returned via the `transfer_status` key and not `domain_status`.

I've fixed the issue, I'll try and clear up the other issues you've reported as well before the next release.

Thanks again!
