### ISSUE TITLE
Version number missing

### ISSUE THREAD

**Issue by greg-digit** [SynergyWholesale/WHMCS-Domains-Module#59]
Hi
copy and paste from the WHMCS module.
- - - - -
Version | This module version: {{VERSION}}
- - - - -

**Comment by Sn0wCrack** [comment]
Hi @greg-digit,

Just checking here, but did you happen download the source code rather than the release file? The source code in this repository has various template variables like {{VERSION}} and {{API}} that get filled in when we build the release of this module.

You should be able to get the latest release files here: https://github.com/SynergyWholesale/WHMCS-Domains-Module/releases/download/v2.2.1/synergy-wholesale-domains-v2.2.1.zip

Or within your Synergy account under: Account Functions > API Information > WHMCS Modules > Download next to the desired module
